version: '3.9'

services:
  university:
    image: 'university-service'
    build:
      context: ./university-service
      dockerfile: Dockerfile
    restart: on-failure
    container_name: 'university-service'
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/final"
      SPRING_DATASOURCE_USERNAME: "misha"
      SPRING_DATASOURCE_PASSWORD: "1111"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "none"
      spring.flyway.url: "jdbc:postgresql://db:5432/final"
      university.service.URL: http://transaction:8082/transactions/

    ports:
      - "8081:8081"

  transaction:
    image: 'transaction-service'
    build:
      context: ./transaction-service
      dockerfile: Dockerfile
    restart: on-failure
    container_name: 'transaction-service'
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/final"
      SPRING_DATASOURCE_USERNAME: "misha"
      SPRING_DATASOURCE_PASSWORD: "1111"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "none"
      spring.flyway.url: "jdbc:postgresql://db:5432/final"

    ports:
      - "8082:8082"

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      POSTGRES_DB: "final"
      POSTGRES_USER: "misha"
      POSTGRES_PASSWORD: "1111"
    volumes:
      - ~/data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
