version: '3.9'

services:
  nats:
      container_name: 'nats'
      image: 'nats'
      ports:
        - "4222:4222"
        - "8222:8222"

  university:
    image: 'university-service'
    build:
      context: ./university-service
      dockerfile: Dockerfile
    restart: on-failure
    container_name: 'university-service'
    depends_on:
      - mongodb
    environment:
      university.service.URL: http://transaction:8082/transactions/
      SPRING.DATA.MONGODB.HOST: mongodb
    ports:
      - "8081:8081"

  transaction:
    image: 'transaction-service'
    build:
      context: ./transaction-service
      dockerfile: Dockerfile
    restart: on-failure
    container_name: 'transaction-service'
    depends_on:
      - mongodb
    environment:
        SPRING.DATA.MONGODB.HOST: mongodb
    ports:
      - "8082:8082"

  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: misha
      MONGO_INITDB_ROOT_PASSWORD: 1111
    volumes:
        - ./data:/mongodata
