/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

val OPENAPI_VER = "1.6.14"
val HTTP_CLIENT_VER = "4.5.13"
val POSTGRES_VER = "42.5.1"
val FLYWAY_CORE_VER = "8.5.13"
val SPRINGBOOT_VER = "2.7.4"

plugins {
    `java-library`
    id("org.springframework.boot") version "2.7.4"
}

repositories {
    mavenCentral()
}

dependencies {
    api("org.springframework.boot:spring-boot-starter:$SPRINGBOOT_VER")
    api("org.flywaydb:flyway-core:$FLYWAY_CORE_VER")
    api("org.springframework.boot:spring-boot-starter-jdbc:$SPRINGBOOT_VER")
    api("org.springframework.boot:spring-boot-starter-web:$SPRINGBOOT_VER")
    api("org.postgresql:postgresql:$POSTGRES_VER")
    api("org.springframework.boot:spring-boot-starter-validation:$SPRINGBOOT_VER")
    api("org.springframework.boot:spring-boot-starter-data-jpa:$SPRINGBOOT_VER")
    api("org.springdoc:springdoc-openapi-ui:$OPENAPI_VER")
    api("org.springframework.boot:spring-boot-starter-security:$SPRINGBOOT_VER")
    api("org.apache.httpcomponents:httpclient:$HTTP_CLIENT_VER")
    testImplementation("org.springframework.boot:spring-boot-starter-test:$SPRINGBOOT_VER")
    testImplementation("org.springframework.security:spring-security-test:$SPRINGBOOT_VER")
}

group = "ua.com.foxminded"
version = "0.0.1-SNAPSHOT"
description = "courseproject"
java.sourceCompatibility = JavaVersion.VERSION_17

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
